packages:
    - 'libs/**'
    - 'apps/**'
    - '!apps/legacy_**'

# Define a catalog of version ranges.
catalog:
  tailwindcss: 3.4.17
  tailwindcss-animate: 1.0.7
  tailwind-merge: 2.6.0
  react: 19.0.0
  react-dom: 19.0.0
  typescript: 5.7.2
  "@types/react": 19.0.1
  "@types/react-dom": 19.0.2
