packages:
    - 'libs/**'
    - 'apps/**'
    - '!apps/legacy_**'

# Define a catalog of version ranges.
catalog:
  react: 19.0.0
  react-dom: 19.0.0
  typescript: 5.7.2
  "@types/react": 19.0.1
  "@types/react-dom": 19.0.2
